/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransactionsLoadsRouteImport } from './routes/_authenticated/transactions/loads'
import { Route as AuthenticatedTransactionsBillsRouteImport } from './routes/_authenticated/transactions/bills'
import { Route as AuthenticatedTransactionsBillEditRouteImport } from './routes/_authenticated/transactions/bill-edit'
import { Route as AuthenticatedTransactionsBillCreateRouteImport } from './routes/_authenticated/transactions/bill-create'
import { Route as AuthenticatedMastersUnitRouteImport } from './routes/_authenticated/masters/unit'
import { Route as AuthenticatedMastersTruckRouteImport } from './routes/_authenticated/masters/truck'
import { Route as AuthenticatedMastersPartyRouteImport } from './routes/_authenticated/masters/party'
import { Route as AuthenticatedMastersNameBoardRouteImport } from './routes/_authenticated/masters/name-board'
import { Route as AuthenticatedMastersLocationRouteImport } from './routes/_authenticated/masters/location'
import { Route as AuthenticatedMastersGoodsRouteImport } from './routes/_authenticated/masters/goods'
import { Route as AuthenticatedMastersFinancialYearRouteImport } from './routes/_authenticated/masters/financial-year'
import { Route as AuthenticatedMainDashboardRouteImport } from './routes/_authenticated/main/dashboard'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin/menu'
import { Route as AuthenticatedTransactionsBillsIndexRouteImport } from './routes/_authenticated/transactions/bills/index'
import { Route as AuthenticatedTransactionsBillEditIndexRouteImport } from './routes/_authenticated/transactions/bill-edit/index'
import { Route as AuthenticatedTransactionsBillEditBillIdRouteImport } from './routes/_authenticated/transactions/bill-edit/$billId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsLoadsRoute =
  AuthenticatedTransactionsLoadsRouteImport.update({
    id: '/transactions/loads',
    path: '/transactions/loads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsBillsRoute =
  AuthenticatedTransactionsBillsRouteImport.update({
    id: '/transactions/bills',
    path: '/transactions/bills',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsBillEditRoute =
  AuthenticatedTransactionsBillEditRouteImport.update({
    id: '/transactions/bill-edit',
    path: '/transactions/bill-edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsBillCreateRoute =
  AuthenticatedTransactionsBillCreateRouteImport.update({
    id: '/transactions/bill-create',
    path: '/transactions/bill-create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersUnitRoute =
  AuthenticatedMastersUnitRouteImport.update({
    id: '/masters/unit',
    path: '/masters/unit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersTruckRoute =
  AuthenticatedMastersTruckRouteImport.update({
    id: '/masters/truck',
    path: '/masters/truck',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersPartyRoute =
  AuthenticatedMastersPartyRouteImport.update({
    id: '/masters/party',
    path: '/masters/party',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersNameBoardRoute =
  AuthenticatedMastersNameBoardRouteImport.update({
    id: '/masters/name-board',
    path: '/masters/name-board',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersLocationRoute =
  AuthenticatedMastersLocationRouteImport.update({
    id: '/masters/location',
    path: '/masters/location',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersGoodsRoute =
  AuthenticatedMastersGoodsRouteImport.update({
    id: '/masters/goods',
    path: '/masters/goods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersFinancialYearRoute =
  AuthenticatedMastersFinancialYearRouteImport.update({
    id: '/masters/financial-year',
    path: '/masters/financial-year',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMainDashboardRoute =
  AuthenticatedMainDashboardRouteImport.update({
    id: '/main/dashboard',
    path: '/main/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsBillsIndexRoute =
  AuthenticatedTransactionsBillsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTransactionsBillsRoute,
  } as any)
const AuthenticatedTransactionsBillEditIndexRoute =
  AuthenticatedTransactionsBillEditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTransactionsBillEditRoute,
  } as any)
const AuthenticatedTransactionsBillEditBillIdRoute =
  AuthenticatedTransactionsBillEditBillIdRouteImport.update({
    id: '/$billId',
    path: '/$billId',
    getParentRoute: () => AuthenticatedTransactionsBillEditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/main/dashboard': typeof AuthenticatedMainDashboardRoute
  '/masters/financial-year': typeof AuthenticatedMastersFinancialYearRoute
  '/masters/goods': typeof AuthenticatedMastersGoodsRoute
  '/masters/location': typeof AuthenticatedMastersLocationRoute
  '/masters/name-board': typeof AuthenticatedMastersNameBoardRoute
  '/masters/party': typeof AuthenticatedMastersPartyRoute
  '/masters/truck': typeof AuthenticatedMastersTruckRoute
  '/masters/unit': typeof AuthenticatedMastersUnitRoute
  '/transactions/bill-create': typeof AuthenticatedTransactionsBillCreateRoute
  '/transactions/bill-edit': typeof AuthenticatedTransactionsBillEditRouteWithChildren
  '/transactions/bills': typeof AuthenticatedTransactionsBillsRouteWithChildren
  '/transactions/loads': typeof AuthenticatedTransactionsLoadsRoute
  '/transactions/bill-edit/$billId': typeof AuthenticatedTransactionsBillEditBillIdRoute
  '/transactions/bill-edit/': typeof AuthenticatedTransactionsBillEditIndexRoute
  '/transactions/bills/': typeof AuthenticatedTransactionsBillsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/main/dashboard': typeof AuthenticatedMainDashboardRoute
  '/masters/financial-year': typeof AuthenticatedMastersFinancialYearRoute
  '/masters/goods': typeof AuthenticatedMastersGoodsRoute
  '/masters/location': typeof AuthenticatedMastersLocationRoute
  '/masters/name-board': typeof AuthenticatedMastersNameBoardRoute
  '/masters/party': typeof AuthenticatedMastersPartyRoute
  '/masters/truck': typeof AuthenticatedMastersTruckRoute
  '/masters/unit': typeof AuthenticatedMastersUnitRoute
  '/transactions/bill-create': typeof AuthenticatedTransactionsBillCreateRoute
  '/transactions/loads': typeof AuthenticatedTransactionsLoadsRoute
  '/transactions/bill-edit/$billId': typeof AuthenticatedTransactionsBillEditBillIdRoute
  '/transactions/bill-edit': typeof AuthenticatedTransactionsBillEditIndexRoute
  '/transactions/bills': typeof AuthenticatedTransactionsBillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/main/dashboard': typeof AuthenticatedMainDashboardRoute
  '/_authenticated/masters/financial-year': typeof AuthenticatedMastersFinancialYearRoute
  '/_authenticated/masters/goods': typeof AuthenticatedMastersGoodsRoute
  '/_authenticated/masters/location': typeof AuthenticatedMastersLocationRoute
  '/_authenticated/masters/name-board': typeof AuthenticatedMastersNameBoardRoute
  '/_authenticated/masters/party': typeof AuthenticatedMastersPartyRoute
  '/_authenticated/masters/truck': typeof AuthenticatedMastersTruckRoute
  '/_authenticated/masters/unit': typeof AuthenticatedMastersUnitRoute
  '/_authenticated/transactions/bill-create': typeof AuthenticatedTransactionsBillCreateRoute
  '/_authenticated/transactions/bill-edit': typeof AuthenticatedTransactionsBillEditRouteWithChildren
  '/_authenticated/transactions/bills': typeof AuthenticatedTransactionsBillsRouteWithChildren
  '/_authenticated/transactions/loads': typeof AuthenticatedTransactionsLoadsRoute
  '/_authenticated/transactions/bill-edit/$billId': typeof AuthenticatedTransactionsBillEditBillIdRoute
  '/_authenticated/transactions/bill-edit/': typeof AuthenticatedTransactionsBillEditIndexRoute
  '/_authenticated/transactions/bills/': typeof AuthenticatedTransactionsBillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/menu'
    | '/main/dashboard'
    | '/masters/financial-year'
    | '/masters/goods'
    | '/masters/location'
    | '/masters/name-board'
    | '/masters/party'
    | '/masters/truck'
    | '/masters/unit'
    | '/transactions/bill-create'
    | '/transactions/bill-edit'
    | '/transactions/bills'
    | '/transactions/loads'
    | '/transactions/bill-edit/$billId'
    | '/transactions/bill-edit/'
    | '/transactions/bills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/admin/menu'
    | '/main/dashboard'
    | '/masters/financial-year'
    | '/masters/goods'
    | '/masters/location'
    | '/masters/name-board'
    | '/masters/party'
    | '/masters/truck'
    | '/masters/unit'
    | '/transactions/bill-create'
    | '/transactions/loads'
    | '/transactions/bill-edit/$billId'
    | '/transactions/bill-edit'
    | '/transactions/bills'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/admin/menu'
    | '/_authenticated/main/dashboard'
    | '/_authenticated/masters/financial-year'
    | '/_authenticated/masters/goods'
    | '/_authenticated/masters/location'
    | '/_authenticated/masters/name-board'
    | '/_authenticated/masters/party'
    | '/_authenticated/masters/truck'
    | '/_authenticated/masters/unit'
    | '/_authenticated/transactions/bill-create'
    | '/_authenticated/transactions/bill-edit'
    | '/_authenticated/transactions/bills'
    | '/_authenticated/transactions/loads'
    | '/_authenticated/transactions/bill-edit/$billId'
    | '/_authenticated/transactions/bill-edit/'
    | '/_authenticated/transactions/bills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/loads': {
      id: '/_authenticated/transactions/loads'
      path: '/transactions/loads'
      fullPath: '/transactions/loads'
      preLoaderRoute: typeof AuthenticatedTransactionsLoadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/bills': {
      id: '/_authenticated/transactions/bills'
      path: '/transactions/bills'
      fullPath: '/transactions/bills'
      preLoaderRoute: typeof AuthenticatedTransactionsBillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/bill-edit': {
      id: '/_authenticated/transactions/bill-edit'
      path: '/transactions/bill-edit'
      fullPath: '/transactions/bill-edit'
      preLoaderRoute: typeof AuthenticatedTransactionsBillEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/bill-create': {
      id: '/_authenticated/transactions/bill-create'
      path: '/transactions/bill-create'
      fullPath: '/transactions/bill-create'
      preLoaderRoute: typeof AuthenticatedTransactionsBillCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/unit': {
      id: '/_authenticated/masters/unit'
      path: '/masters/unit'
      fullPath: '/masters/unit'
      preLoaderRoute: typeof AuthenticatedMastersUnitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/truck': {
      id: '/_authenticated/masters/truck'
      path: '/masters/truck'
      fullPath: '/masters/truck'
      preLoaderRoute: typeof AuthenticatedMastersTruckRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/party': {
      id: '/_authenticated/masters/party'
      path: '/masters/party'
      fullPath: '/masters/party'
      preLoaderRoute: typeof AuthenticatedMastersPartyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/name-board': {
      id: '/_authenticated/masters/name-board'
      path: '/masters/name-board'
      fullPath: '/masters/name-board'
      preLoaderRoute: typeof AuthenticatedMastersNameBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/location': {
      id: '/_authenticated/masters/location'
      path: '/masters/location'
      fullPath: '/masters/location'
      preLoaderRoute: typeof AuthenticatedMastersLocationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/goods': {
      id: '/_authenticated/masters/goods'
      path: '/masters/goods'
      fullPath: '/masters/goods'
      preLoaderRoute: typeof AuthenticatedMastersGoodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/financial-year': {
      id: '/_authenticated/masters/financial-year'
      path: '/masters/financial-year'
      fullPath: '/masters/financial-year'
      preLoaderRoute: typeof AuthenticatedMastersFinancialYearRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/main/dashboard': {
      id: '/_authenticated/main/dashboard'
      path: '/main/dashboard'
      fullPath: '/main/dashboard'
      preLoaderRoute: typeof AuthenticatedMainDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/bills/': {
      id: '/_authenticated/transactions/bills/'
      path: '/'
      fullPath: '/transactions/bills/'
      preLoaderRoute: typeof AuthenticatedTransactionsBillsIndexRouteImport
      parentRoute: typeof AuthenticatedTransactionsBillsRoute
    }
    '/_authenticated/transactions/bill-edit/': {
      id: '/_authenticated/transactions/bill-edit/'
      path: '/'
      fullPath: '/transactions/bill-edit/'
      preLoaderRoute: typeof AuthenticatedTransactionsBillEditIndexRouteImport
      parentRoute: typeof AuthenticatedTransactionsBillEditRoute
    }
    '/_authenticated/transactions/bill-edit/$billId': {
      id: '/_authenticated/transactions/bill-edit/$billId'
      path: '/$billId'
      fullPath: '/transactions/bill-edit/$billId'
      preLoaderRoute: typeof AuthenticatedTransactionsBillEditBillIdRouteImport
      parentRoute: typeof AuthenticatedTransactionsBillEditRoute
    }
  }
}

interface AuthenticatedTransactionsBillEditRouteChildren {
  AuthenticatedTransactionsBillEditBillIdRoute: typeof AuthenticatedTransactionsBillEditBillIdRoute
  AuthenticatedTransactionsBillEditIndexRoute: typeof AuthenticatedTransactionsBillEditIndexRoute
}

const AuthenticatedTransactionsBillEditRouteChildren: AuthenticatedTransactionsBillEditRouteChildren =
  {
    AuthenticatedTransactionsBillEditBillIdRoute:
      AuthenticatedTransactionsBillEditBillIdRoute,
    AuthenticatedTransactionsBillEditIndexRoute:
      AuthenticatedTransactionsBillEditIndexRoute,
  }

const AuthenticatedTransactionsBillEditRouteWithChildren =
  AuthenticatedTransactionsBillEditRoute._addFileChildren(
    AuthenticatedTransactionsBillEditRouteChildren,
  )

interface AuthenticatedTransactionsBillsRouteChildren {
  AuthenticatedTransactionsBillsIndexRoute: typeof AuthenticatedTransactionsBillsIndexRoute
}

const AuthenticatedTransactionsBillsRouteChildren: AuthenticatedTransactionsBillsRouteChildren =
  {
    AuthenticatedTransactionsBillsIndexRoute:
      AuthenticatedTransactionsBillsIndexRoute,
  }

const AuthenticatedTransactionsBillsRouteWithChildren =
  AuthenticatedTransactionsBillsRoute._addFileChildren(
    AuthenticatedTransactionsBillsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedMainDashboardRoute: typeof AuthenticatedMainDashboardRoute
  AuthenticatedMastersFinancialYearRoute: typeof AuthenticatedMastersFinancialYearRoute
  AuthenticatedMastersGoodsRoute: typeof AuthenticatedMastersGoodsRoute
  AuthenticatedMastersLocationRoute: typeof AuthenticatedMastersLocationRoute
  AuthenticatedMastersNameBoardRoute: typeof AuthenticatedMastersNameBoardRoute
  AuthenticatedMastersPartyRoute: typeof AuthenticatedMastersPartyRoute
  AuthenticatedMastersTruckRoute: typeof AuthenticatedMastersTruckRoute
  AuthenticatedMastersUnitRoute: typeof AuthenticatedMastersUnitRoute
  AuthenticatedTransactionsBillCreateRoute: typeof AuthenticatedTransactionsBillCreateRoute
  AuthenticatedTransactionsBillEditRoute: typeof AuthenticatedTransactionsBillEditRouteWithChildren
  AuthenticatedTransactionsBillsRoute: typeof AuthenticatedTransactionsBillsRouteWithChildren
  AuthenticatedTransactionsLoadsRoute: typeof AuthenticatedTransactionsLoadsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
  AuthenticatedMainDashboardRoute: AuthenticatedMainDashboardRoute,
  AuthenticatedMastersFinancialYearRoute:
    AuthenticatedMastersFinancialYearRoute,
  AuthenticatedMastersGoodsRoute: AuthenticatedMastersGoodsRoute,
  AuthenticatedMastersLocationRoute: AuthenticatedMastersLocationRoute,
  AuthenticatedMastersNameBoardRoute: AuthenticatedMastersNameBoardRoute,
  AuthenticatedMastersPartyRoute: AuthenticatedMastersPartyRoute,
  AuthenticatedMastersTruckRoute: AuthenticatedMastersTruckRoute,
  AuthenticatedMastersUnitRoute: AuthenticatedMastersUnitRoute,
  AuthenticatedTransactionsBillCreateRoute:
    AuthenticatedTransactionsBillCreateRoute,
  AuthenticatedTransactionsBillEditRoute:
    AuthenticatedTransactionsBillEditRouteWithChildren,
  AuthenticatedTransactionsBillsRoute:
    AuthenticatedTransactionsBillsRouteWithChildren,
  AuthenticatedTransactionsLoadsRoute: AuthenticatedTransactionsLoadsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
