/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMastersUnitRouteImport } from './routes/_authenticated/masters/unit'
import { Route as AuthenticatedMastersTruckRouteImport } from './routes/_authenticated/masters/truck'
import { Route as AuthenticatedMastersPartyRouteImport } from './routes/_authenticated/masters/party'
import { Route as AuthenticatedMastersNameBoardRouteImport } from './routes/_authenticated/masters/name-board'
import { Route as AuthenticatedMastersLocationRouteImport } from './routes/_authenticated/masters/location'
import { Route as AuthenticatedMastersGoodsRouteImport } from './routes/_authenticated/masters/goods'
import { Route as AuthenticatedMainDashboardRouteImport } from './routes/_authenticated/main/dashboard'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin/menu'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMastersUnitRoute =
  AuthenticatedMastersUnitRouteImport.update({
    id: '/masters/unit',
    path: '/masters/unit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersTruckRoute =
  AuthenticatedMastersTruckRouteImport.update({
    id: '/masters/truck',
    path: '/masters/truck',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersPartyRoute =
  AuthenticatedMastersPartyRouteImport.update({
    id: '/masters/party',
    path: '/masters/party',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersNameBoardRoute =
  AuthenticatedMastersNameBoardRouteImport.update({
    id: '/masters/name-board',
    path: '/masters/name-board',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersLocationRoute =
  AuthenticatedMastersLocationRouteImport.update({
    id: '/masters/location',
    path: '/masters/location',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersGoodsRoute =
  AuthenticatedMastersGoodsRouteImport.update({
    id: '/masters/goods',
    path: '/masters/goods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMainDashboardRoute =
  AuthenticatedMainDashboardRouteImport.update({
    id: '/main/dashboard',
    path: '/main/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/main/dashboard': typeof AuthenticatedMainDashboardRoute
  '/masters/goods': typeof AuthenticatedMastersGoodsRoute
  '/masters/location': typeof AuthenticatedMastersLocationRoute
  '/masters/name-board': typeof AuthenticatedMastersNameBoardRoute
  '/masters/party': typeof AuthenticatedMastersPartyRoute
  '/masters/truck': typeof AuthenticatedMastersTruckRoute
  '/masters/unit': typeof AuthenticatedMastersUnitRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/main/dashboard': typeof AuthenticatedMainDashboardRoute
  '/masters/goods': typeof AuthenticatedMastersGoodsRoute
  '/masters/location': typeof AuthenticatedMastersLocationRoute
  '/masters/name-board': typeof AuthenticatedMastersNameBoardRoute
  '/masters/party': typeof AuthenticatedMastersPartyRoute
  '/masters/truck': typeof AuthenticatedMastersTruckRoute
  '/masters/unit': typeof AuthenticatedMastersUnitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/main/dashboard': typeof AuthenticatedMainDashboardRoute
  '/_authenticated/masters/goods': typeof AuthenticatedMastersGoodsRoute
  '/_authenticated/masters/location': typeof AuthenticatedMastersLocationRoute
  '/_authenticated/masters/name-board': typeof AuthenticatedMastersNameBoardRoute
  '/_authenticated/masters/party': typeof AuthenticatedMastersPartyRoute
  '/_authenticated/masters/truck': typeof AuthenticatedMastersTruckRoute
  '/_authenticated/masters/unit': typeof AuthenticatedMastersUnitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/menu'
    | '/main/dashboard'
    | '/masters/goods'
    | '/masters/location'
    | '/masters/name-board'
    | '/masters/party'
    | '/masters/truck'
    | '/masters/unit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/admin/menu'
    | '/main/dashboard'
    | '/masters/goods'
    | '/masters/location'
    | '/masters/name-board'
    | '/masters/party'
    | '/masters/truck'
    | '/masters/unit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/admin/menu'
    | '/_authenticated/main/dashboard'
    | '/_authenticated/masters/goods'
    | '/_authenticated/masters/location'
    | '/_authenticated/masters/name-board'
    | '/_authenticated/masters/party'
    | '/_authenticated/masters/truck'
    | '/_authenticated/masters/unit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/unit': {
      id: '/_authenticated/masters/unit'
      path: '/masters/unit'
      fullPath: '/masters/unit'
      preLoaderRoute: typeof AuthenticatedMastersUnitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/truck': {
      id: '/_authenticated/masters/truck'
      path: '/masters/truck'
      fullPath: '/masters/truck'
      preLoaderRoute: typeof AuthenticatedMastersTruckRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/party': {
      id: '/_authenticated/masters/party'
      path: '/masters/party'
      fullPath: '/masters/party'
      preLoaderRoute: typeof AuthenticatedMastersPartyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/name-board': {
      id: '/_authenticated/masters/name-board'
      path: '/masters/name-board'
      fullPath: '/masters/name-board'
      preLoaderRoute: typeof AuthenticatedMastersNameBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/location': {
      id: '/_authenticated/masters/location'
      path: '/masters/location'
      fullPath: '/masters/location'
      preLoaderRoute: typeof AuthenticatedMastersLocationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/goods': {
      id: '/_authenticated/masters/goods'
      path: '/masters/goods'
      fullPath: '/masters/goods'
      preLoaderRoute: typeof AuthenticatedMastersGoodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/main/dashboard': {
      id: '/_authenticated/main/dashboard'
      path: '/main/dashboard'
      fullPath: '/main/dashboard'
      preLoaderRoute: typeof AuthenticatedMainDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedMainDashboardRoute: typeof AuthenticatedMainDashboardRoute
  AuthenticatedMastersGoodsRoute: typeof AuthenticatedMastersGoodsRoute
  AuthenticatedMastersLocationRoute: typeof AuthenticatedMastersLocationRoute
  AuthenticatedMastersNameBoardRoute: typeof AuthenticatedMastersNameBoardRoute
  AuthenticatedMastersPartyRoute: typeof AuthenticatedMastersPartyRoute
  AuthenticatedMastersTruckRoute: typeof AuthenticatedMastersTruckRoute
  AuthenticatedMastersUnitRoute: typeof AuthenticatedMastersUnitRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
  AuthenticatedMainDashboardRoute: AuthenticatedMainDashboardRoute,
  AuthenticatedMastersGoodsRoute: AuthenticatedMastersGoodsRoute,
  AuthenticatedMastersLocationRoute: AuthenticatedMastersLocationRoute,
  AuthenticatedMastersNameBoardRoute: AuthenticatedMastersNameBoardRoute,
  AuthenticatedMastersPartyRoute: AuthenticatedMastersPartyRoute,
  AuthenticatedMastersTruckRoute: AuthenticatedMastersTruckRoute,
  AuthenticatedMastersUnitRoute: AuthenticatedMastersUnitRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
