import type { BillOtherItem } from '@/types/billOther';
import type { BillPayBy } from '@/types/entity/bill';

export type BillLoadFormLine = {
  loadId?: number | null;
  loadNumber: number;
  consignorId: number | null;
  consignorName: string;
  consigneeId: number | null;
  consigneeName: string;
  asPerBill: boolean;
  toId: number | null;
  toLocationName: string;
  goodsId: number | null;
  goodsName: string;
  unitId: number | null;
  unitName: string;
  weightOrQuantity: number | '';
  ratePerUnit: number | '';
  freight: number | '';
  advance: number | '';
  topay: number | '';
  balance: number | '';
};

export type BillFormValues = {
  billId?: number | null;
  billNumber: string;
  billDate: string;
  fromId: number | null;
  fromLocationName: string;
  truckId: number | null;
  truckNumber: string;
  nameBoardName: string;
  ownerName: string;
  ownerMobile: string;
  driverName: string;
  driverMobile1: string;
  driverMobile2: string;
  totalFreight: number | '';
  commission: number | '';
  crossing: number | '';
  handLoan: number | '';
  truckLoan: boolean;
  payBy: BillPayBy | null;
  paidName: string;
  paidMobile: string;
  officeMamul: number | '';
  tapalMamul: number | '';
  diesel: number | '';
  others: BillOtherItem[];
  total: number | '';
  isCancelled: boolean;
  loads: BillLoadFormLine[];
};
