// <auto-generated />
using System;
using System.Collections.Generic;
using Domain.Transactions;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260610120000_BillPaidName")]
    partial class BillPaidName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Access.AppMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuId"));

                    b.Property<string>("Badge")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("badge");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<bool>("DefaultExpanded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("default_expanded");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("menu_code");

                    b.Property<string>("MenuGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("main")
                        .HasColumnName("menu_group");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_menu_id");

                    b.Property<string>("RoutePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("route_path");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Tooltip")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tooltip");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("MenuId")
                        .HasName("pk_app_menu");

                    b.HasIndex("MenuCode")
                        .IsUnique()
                        .HasDatabaseName("ix_app_menu_menu_code");

                    b.HasIndex("ParentMenuId")
                        .HasDatabaseName("ix_app_menu_parent_menu_id");

                    b.HasIndex("RoutePath")
                        .IsUnique()
                        .HasDatabaseName("ix_app_menu_route_path");

                    b.ToTable("app_menu", "public");
                });

            modelBuilder.Entity("Domain.Access.AppRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_code");

                    b.HasKey("RoleId")
                        .HasName("pk_app_role");

                    b.ToTable("app_role", "public");
                });

            modelBuilder.Entity("Domain.Access.AppRoleMenu", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDisplayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_displayed");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("RoleId", "MenuId")
                        .HasName("pk_app_role_menu");

                    b.ToTable("app_role_menu", "public");
                });

            modelBuilder.Entity("Domain.Masters.FinancialYear", b =>
                {
                    b.Property<int>("FinancialYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("financial_year_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FinancialYearId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("FinancialYearId")
                        .HasName("pk_financial_year");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_year_code");

                    b.ToTable("financial_year", "public");
                });

            modelBuilder.Entity("Domain.Masters.Goods", b =>
                {
                    b.Property<int>("GoodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("goods_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GoodsId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("GoodsId")
                        .HasName("pk_goods");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_goods_code");

                    b.ToTable("goods", "public");
                });

            modelBuilder.Entity("Domain.Masters.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("LocationId")
                        .HasName("pk_location");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_location_code");

                    b.ToTable("location", "public");
                });

            modelBuilder.Entity("Domain.Masters.NameBoard", b =>
                {
                    b.Property<int>("NameBoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("name_board_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NameBoardId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_name");

                    b.Property<string>("OwnerPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("owner_phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("NameBoardId")
                        .HasName("pk_name_board");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_name_board_code");

                    b.ToTable("name_board", "public");
                });

            modelBuilder.Entity("Domain.Masters.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("PartyId")
                        .HasName("pk_party");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_party_code");

                    b.ToTable("party", "public");
                });

            modelBuilder.Entity("Domain.Masters.Truck", b =>
                {
                    b.Property<int>("TruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("truck_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TruckId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<int>("NameBoardId")
                        .HasColumnType("integer")
                        .HasColumnName("name_board_id");

                    b.Property<string>("TruckNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("truck_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("TruckId")
                        .HasName("pk_truck");

                    b.HasIndex("NameBoardId")
                        .HasDatabaseName("ix_truck_name_board_id");

                    b.HasIndex("TruckNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_truck_truck_number");

                    b.ToTable("truck", "public");
                });

            modelBuilder.Entity("Domain.Masters.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsFixed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_fixed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("UnitId")
                        .HasName("pk_unit");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_code");

                    b.ToTable("unit", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entity_kind");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_name");

                    b.Property<string>("PersistMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("persist_mode");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("table_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("EntityId")
                        .HasName("pk_app_entity");

                    b.HasIndex("EntityName")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_entity_name");

                    b.HasIndex("TableName")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_table_name");

                    b.ToTable("app_entity", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityField", b =>
                {
                    b.Property<int>("EntityFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_field_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityFieldId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<int>("FieldDataTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("field_data_type_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field_name");

                    b.Property<bool>("Filterable")
                        .HasColumnType("boolean")
                        .HasColumnName("filterable");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.Property<int?>("MinLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_length");

                    b.Property<bool>("Selectable")
                        .HasColumnType("boolean")
                        .HasColumnName("selectable");

                    b.Property<bool>("Sortable")
                        .HasColumnType("boolean")
                        .HasColumnName("sortable");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationRegex")
                        .HasColumnType("text")
                        .HasColumnName("validation_regex");

                    b.Property<bool>("Writable")
                        .HasColumnType("boolean")
                        .HasColumnName("writable");

                    b.HasKey("EntityFieldId")
                        .HasName("pk_app_entity_field");

                    b.HasIndex("FieldDataTypeId")
                        .HasDatabaseName("ix_app_entity_field_field_data_type_id");

                    b.HasIndex("EntityId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_field_entity_id_field_name");

                    b.ToTable("app_entity_field", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreen", b =>
                {
                    b.Property<int>("EntityScreenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_screen_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityScreenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("EntityScreenId")
                        .HasName("pk_app_entity_screen");

                    b.HasIndex("MenuId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_screen_menu_id");

                    b.HasIndex("EntityId", "MenuId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_screen_entity_id_menu_id");

                    b.ToTable("app_entity_screen", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreenColumn", b =>
                {
                    b.Property<int>("EntityScreenColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_screen_column_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityScreenColumnId"));

                    b.Property<string>("Align")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("align");

                    b.Property<bool?>("AllowSort")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_sort");

                    b.Property<string>("ColumnComponent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("column_component");

                    b.Property<int?>("ColumnWidthPercent")
                        .HasColumnType("integer")
                        .HasColumnName("column_width_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayLabel")
                        .HasColumnType("text")
                        .HasColumnName("display_label");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("EntityFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_field_id");

                    b.Property<int>("EntityScreenId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_screen_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityScreenColumnId")
                        .HasName("pk_app_entity_screen_column");

                    b.HasIndex("EntityFieldId")
                        .HasDatabaseName("ix_app_entity_screen_column_entity_field_id");

                    b.HasIndex("EntityScreenId", "EntityFieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_screen_column_entity_screen_id_entity_field_id");

                    b.ToTable("app_entity_screen_column", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreenField", b =>
                {
                    b.Property<int>("EntityScreenFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_screen_field_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityScreenFieldId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayLabel")
                        .HasColumnType("text")
                        .HasColumnName("display_label");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("EntityFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_field_id");

                    b.Property<int>("EntityScreenId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_screen_id");

                    b.Property<string>("FieldComponent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field_component");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read_only");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityScreenFieldId")
                        .HasName("pk_app_entity_screen_field");

                    b.HasIndex("EntityFieldId")
                        .HasDatabaseName("ix_app_entity_screen_field_entity_field_id");

                    b.HasIndex("EntityScreenId", "EntityFieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_screen_field_entity_screen_id_entity_field_id");

                    b.ToTable("app_entity_screen_field", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppFieldDataType", b =>
                {
                    b.Property<int>("FieldDataTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("field_data_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FieldDataTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FieldDataTypeId")
                        .HasName("pk_app_field_data_type");

                    b.HasIndex("TypeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_app_field_data_type_type_code");

                    b.ToTable("app_field_data_type", "public");
                });

            modelBuilder.Entity("Domain.Transactions.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillId"));

                    b.Property<DateOnly>("BillDate")
                        .HasColumnType("date")
                        .HasColumnName("bill_date");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bill_number");

                    b.Property<decimal>("Commission")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("commission");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Crossing")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("crossing");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Diesel")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("diesel");

                    b.Property<string>("DriverMobile")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("driver_mobile");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("driver_name");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("integer")
                        .HasColumnName("financial_year_id");

                    b.Property<int>("FromId")
                        .HasColumnType("integer")
                        .HasColumnName("from_id");

                    b.Property<decimal>("HandLoan")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("hand_loan");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cancelled");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<decimal>("OfficeMamul")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("office_mamul");

                    b.Property<List<BillOtherItem>>("Others")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("others")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("PaidMobile")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("paid_mobile");

                    b.Property<string>("PaidName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("paid_name");

                    b.Property<string>("PayBy")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("pay_by");

                    b.Property<decimal>("TapalMamul")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tapal_mamul");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalFreight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_freight");

                    b.Property<int>("TruckId")
                        .HasColumnType("integer")
                        .HasColumnName("truck_id");

                    b.Property<bool>("TruckLoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("truck_loan");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("BillId")
                        .HasName("pk_bills");

                    b.HasIndex("FinancialYearId")
                        .HasDatabaseName("ix_bills_financial_year_id");

                    b.HasIndex("FromId")
                        .HasDatabaseName("ix_bills_from_id");

                    b.HasIndex("TruckId")
                        .HasDatabaseName("ix_bills_truck_id");

                    b.HasIndex("FinancialYearId", "BillNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_bills_financial_year_id_bill_number");

                    b.ToTable("bills", "public");
                });

            modelBuilder.Entity("Domain.Transactions.BillListRow", b =>
                {
                    b.Property<DateOnly>("BillDate")
                        .HasColumnType("date")
                        .HasColumnName("bill_date");

                    b.Property<int>("BillId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bill_number");

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric")
                        .HasColumnName("commission");

                    b.Property<decimal>("Crossing")
                        .HasColumnType("numeric")
                        .HasColumnName("crossing");

                    b.Property<decimal>("Diesel")
                        .HasColumnType("numeric")
                        .HasColumnName("diesel");

                    b.Property<string>("DriverMobile")
                        .HasColumnType("text")
                        .HasColumnName("driver_mobile");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("driver_name");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("integer")
                        .HasColumnName("financial_year_id");

                    b.Property<int>("FromId")
                        .HasColumnType("integer")
                        .HasColumnName("from_id");

                    b.Property<string>("FromLocationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_location_name");

                    b.Property<decimal>("HandLoan")
                        .HasColumnType("numeric")
                        .HasColumnName("hand_loan");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<string>("NameBoardName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_board_name");

                    b.Property<decimal>("OfficeMamul")
                        .HasColumnType("numeric")
                        .HasColumnName("office_mamul");

                    b.Property<decimal>("Others")
                        .HasColumnType("numeric")
                        .HasColumnName("others");

                    b.Property<string>("OwnerMobile")
                        .HasColumnType("text")
                        .HasColumnName("owner_mobile");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<string>("PaidMobile")
                        .HasColumnType("text")
                        .HasColumnName("paid_mobile");

                    b.Property<string>("PaidName")
                        .HasColumnType("text")
                        .HasColumnName("paid_name");

                    b.Property<string>("PayBy")
                        .HasColumnType("text")
                        .HasColumnName("pay_by");

                    b.Property<decimal>("TapalMamul")
                        .HasColumnType("numeric")
                        .HasColumnName("tapal_mamul");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalFreight")
                        .HasColumnType("numeric")
                        .HasColumnName("total_freight");

                    b.Property<int>("TruckId")
                        .HasColumnType("integer")
                        .HasColumnName("truck_id");

                    b.Property<bool>("TruckLoan")
                        .HasColumnType("boolean")
                        .HasColumnName("truck_loan");

                    b.Property<string>("TruckNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("truck_number");

                    b.ToTable((string)null);

                    b.ToView("v_bills", "public");
                });

            modelBuilder.Entity("Domain.Transactions.Load", b =>
                {
                    b.Property<int>("LoadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("load_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoadId"));

                    b.Property<decimal>("Advance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("advance");

                    b.Property<bool>("AsPerBill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("as_per_bill");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<int>("BillId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    b.Property<int?>("ConsigneeId")
                        .HasColumnType("integer")
                        .HasColumnName("consignee_id");

                    b.Property<int>("ConsignorId")
                        .HasColumnType("integer")
                        .HasColumnName("consignor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("integer")
                        .HasColumnName("financial_year_id");

                    b.Property<decimal>("Freight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("freight");

                    b.Property<int>("GoodsId")
                        .HasColumnType("integer")
                        .HasColumnName("goods_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<int>("LoadNumber")
                        .HasColumnType("integer")
                        .HasColumnName("load_number");

                    b.Property<decimal>("RatePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("rate_per_unit");

                    b.Property<int>("ToId")
                        .HasColumnType("integer")
                        .HasColumnName("to_id");

                    b.Property<decimal>("Topay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("topay");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("WeightOrQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("weight_or_quantity");

                    b.HasKey("LoadId")
                        .HasName("pk_loads");

                    b.HasIndex("BillId")
                        .HasDatabaseName("ix_loads_bill_id");

                    b.HasIndex("FinancialYearId")
                        .HasDatabaseName("ix_loads_financial_year_id");

                    b.HasIndex("BillId", "LoadNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_loads_bill_id_load_number_active")
                        .HasFilter("is_active = true");

                    b.ToTable("loads", "public");
                });

            modelBuilder.Entity("Domain.Transactions.LoadListRow", b =>
                {
                    b.Property<decimal>("Advance")
                        .HasColumnType("numeric")
                        .HasColumnName("advance");

                    b.Property<bool>("AsPerBill")
                        .HasColumnType("boolean")
                        .HasColumnName("as_per_bill");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<int>("BillId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bill_number");

                    b.Property<int?>("ConsigneeId")
                        .HasColumnType("integer")
                        .HasColumnName("consignee_id");

                    b.Property<string>("ConsigneeName")
                        .HasColumnType("text")
                        .HasColumnName("consignee_name");

                    b.Property<int>("ConsignorId")
                        .HasColumnType("integer")
                        .HasColumnName("consignor_id");

                    b.Property<string>("ConsignorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consignor_name");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("integer")
                        .HasColumnName("financial_year_id");

                    b.Property<decimal>("Freight")
                        .HasColumnType("numeric")
                        .HasColumnName("freight");

                    b.Property<int>("GoodsId")
                        .HasColumnType("integer")
                        .HasColumnName("goods_id");

                    b.Property<string>("GoodsName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("goods_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LoadId")
                        .HasColumnType("integer")
                        .HasColumnName("load_id");

                    b.Property<int>("LoadNumber")
                        .HasColumnType("integer")
                        .HasColumnName("load_number");

                    b.Property<decimal>("RatePerUnit")
                        .HasColumnType("numeric")
                        .HasColumnName("rate_per_unit");

                    b.Property<int>("ToId")
                        .HasColumnType("integer")
                        .HasColumnName("to_id");

                    b.Property<string>("ToLocationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_location_name");

                    b.Property<decimal>("Topay")
                        .HasColumnType("numeric")
                        .HasColumnName("topay");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_name");

                    b.Property<decimal>("WeightOrQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_or_quantity");

                    b.ToTable((string)null);

                    b.ToView("v_loads", "public");
                });

            modelBuilder.Entity("Domain.Access.AppMenu", b =>
                {
                    b.HasOne("Domain.Access.AppMenu", null)
                        .WithMany()
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_app_menu_app_menu_parent_menu_id");
                });

            modelBuilder.Entity("Domain.Masters.Truck", b =>
                {
                    b.HasOne("Domain.Masters.NameBoard", "NameBoard")
                        .WithMany("Trucks")
                        .HasForeignKey("NameBoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_truck_name_board_name_board_id");

                    b.Navigation("NameBoard");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityField", b =>
                {
                    b.HasOne("Domain.Registry.AppEntity", "Entity")
                        .WithMany("Fields")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_field_app_entity_entity_id");

                    b.HasOne("Domain.Registry.AppFieldDataType", "FieldDataType")
                        .WithMany("EntityFields")
                        .HasForeignKey("FieldDataTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_field_app_field_data_type_field_data_type_id");

                    b.Navigation("Entity");

                    b.Navigation("FieldDataType");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreen", b =>
                {
                    b.HasOne("Domain.Registry.AppEntity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_screen_app_entity_entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreenColumn", b =>
                {
                    b.HasOne("Domain.Registry.AppEntityField", "EntityField")
                        .WithMany()
                        .HasForeignKey("EntityFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_screen_column_app_entity_field_entity_field_id");

                    b.HasOne("Domain.Registry.AppEntityScreen", "Screen")
                        .WithMany("Columns")
                        .HasForeignKey("EntityScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_screen_column_app_entity_screen_entity_screen_id");

                    b.Navigation("EntityField");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreenField", b =>
                {
                    b.HasOne("Domain.Registry.AppEntityField", "EntityField")
                        .WithMany()
                        .HasForeignKey("EntityFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_screen_field_app_entity_field_entity_field_id");

                    b.HasOne("Domain.Registry.AppEntityScreen", "Screen")
                        .WithMany("Fields")
                        .HasForeignKey("EntityScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_screen_field_app_entity_screen_entity_screen_id");

                    b.Navigation("EntityField");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("Domain.Transactions.Load", b =>
                {
                    b.HasOne("Domain.Transactions.Bill", "Bill")
                        .WithMany("Loads")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loads_bills_bill_id");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Domain.Masters.NameBoard", b =>
                {
                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("Domain.Registry.AppEntity", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreen", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Domain.Registry.AppFieldDataType", b =>
                {
                    b.Navigation("EntityFields");
                });

            modelBuilder.Entity("Domain.Transactions.Bill", b =>
                {
                    b.Navigation("Loads");
                });
#pragma warning restore 612, 618
        }
    }
}
