// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260523121714_AddNameBoard")]
    partial class AddNameBoard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Masters.NameBoard", b =>
                {
                    b.Property<int>("NameBoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("name_board_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NameBoardId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_name");

                    b.Property<string>("OwnerPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("owner_phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("NameBoardId")
                        .HasName("pk_name_board");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_name_board_code");

                    b.ToTable("name_board", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entity_kind");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_name");

                    b.Property<string>("PersistMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("persist_mode");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("table_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("EntityId")
                        .HasName("pk_app_entity");

                    b.HasIndex("EntityName")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_entity_name");

                    b.HasIndex("TableName")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_table_name");

                    b.ToTable("app_entity", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityDependency", b =>
                {
                    b.Property<int>("EntityDependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_dependency_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityDependencyId"));

                    b.Property<int>("ChildEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("child_entity_id");

                    b.Property<string>("ChildFkColumn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("child_fk_column");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ParentEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_entity_id");

                    b.HasKey("EntityDependencyId")
                        .HasName("pk_app_entity_dependency");

                    b.HasIndex("ChildEntityId")
                        .HasDatabaseName("ix_app_entity_dependency_child_entity_id");

                    b.HasIndex("ParentEntityId", "ChildEntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_dependency_parent_entity_id_child_entity_id");

                    b.ToTable("app_entity_dependency", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityField", b =>
                {
                    b.Property<int>("EntityFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_field_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityFieldId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field_name");

                    b.Property<bool>("Filterable")
                        .HasColumnType("boolean")
                        .HasColumnName("filterable");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.Property<int?>("MinLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_length");

                    b.Property<bool>("Selectable")
                        .HasColumnType("boolean")
                        .HasColumnName("selectable");

                    b.Property<bool>("Sortable")
                        .HasColumnType("boolean")
                        .HasColumnName("sortable");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationRegex")
                        .HasColumnType("text")
                        .HasColumnName("validation_regex");

                    b.Property<bool>("Writable")
                        .HasColumnType("boolean")
                        .HasColumnName("writable");

                    b.HasKey("EntityFieldId")
                        .HasName("pk_app_entity_field");

                    b.HasIndex("EntityId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_field_entity_id_field_name");

                    b.ToTable("app_entity_field", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreen", b =>
                {
                    b.Property<int>("EntityScreenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_screen_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityScreenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("EntityScreenId")
                        .HasName("pk_app_entity_screen");

                    b.HasIndex("MenuId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_screen_menu_id");

                    b.HasIndex("EntityId", "MenuId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_screen_entity_id_menu_id");

                    b.ToTable("app_entity_screen", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreenColumn", b =>
                {
                    b.Property<int>("EntityScreenColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_screen_column_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityScreenColumnId"));

                    b.Property<string>("Align")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("align");

                    b.Property<bool?>("AllowSort")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_sort");

                    b.Property<int?>("ColumnWidth")
                        .HasColumnType("integer")
                        .HasColumnName("column_width");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayLabel")
                        .HasColumnType("text")
                        .HasColumnName("display_label");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("EntityFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_field_id");

                    b.Property<int>("EntityScreenId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_screen_id");

                    b.Property<string>("FormatHint")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("format_hint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<int?>("MinWidth")
                        .HasColumnType("integer")
                        .HasColumnName("min_width");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityScreenColumnId")
                        .HasName("pk_app_entity_screen_column");

                    b.HasIndex("EntityFieldId")
                        .HasDatabaseName("ix_app_entity_screen_column_entity_field_id");

                    b.HasIndex("EntityScreenId", "EntityFieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_screen_column_entity_screen_id_entity_field_id");

                    b.ToTable("app_entity_screen_column", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreenField", b =>
                {
                    b.Property<int>("EntityScreenFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_screen_field_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityScreenFieldId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayLabel")
                        .HasColumnType("text")
                        .HasColumnName("display_label");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("EntityFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_field_id");

                    b.Property<int>("EntityScreenId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_screen_id");

                    b.Property<string>("FormatHint")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("format_hint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read_only");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityScreenFieldId")
                        .HasName("pk_app_entity_screen_field");

                    b.HasIndex("EntityFieldId")
                        .HasDatabaseName("ix_app_entity_screen_field_entity_field_id");

                    b.HasIndex("EntityScreenId", "EntityFieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_entity_screen_field_entity_screen_id_entity_field_id");

                    b.ToTable("app_entity_screen_field", "public");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityDependency", b =>
                {
                    b.HasOne("Domain.Registry.AppEntity", "ChildEntity")
                        .WithMany()
                        .HasForeignKey("ChildEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_dependency_app_entity_child_entity_id");

                    b.HasOne("Domain.Registry.AppEntity", "ParentEntity")
                        .WithMany()
                        .HasForeignKey("ParentEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_dependency_app_entity_parent_entity_id");

                    b.Navigation("ChildEntity");

                    b.Navigation("ParentEntity");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityField", b =>
                {
                    b.HasOne("Domain.Registry.AppEntity", "Entity")
                        .WithMany("Fields")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_field_app_entity_entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreen", b =>
                {
                    b.HasOne("Domain.Registry.AppEntity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_screen_app_entity_entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreenColumn", b =>
                {
                    b.HasOne("Domain.Registry.AppEntityField", "EntityField")
                        .WithMany()
                        .HasForeignKey("EntityFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_screen_column_app_entity_field_entity_field_id");

                    b.HasOne("Domain.Registry.AppEntityScreen", "Screen")
                        .WithMany("Columns")
                        .HasForeignKey("EntityScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_screen_column_app_entity_screen_entity_screen_id");

                    b.Navigation("EntityField");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreenField", b =>
                {
                    b.HasOne("Domain.Registry.AppEntityField", "EntityField")
                        .WithMany()
                        .HasForeignKey("EntityFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_screen_field_app_entity_field_entity_field_id");

                    b.HasOne("Domain.Registry.AppEntityScreen", "Screen")
                        .WithMany("Fields")
                        .HasForeignKey("EntityScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_entity_screen_field_app_entity_screen_entity_screen_id");

                    b.Navigation("EntityField");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("Domain.Registry.AppEntity", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Domain.Registry.AppEntityScreen", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
