export * from '@/service/query/access';
export * from '@/service/query/goods';
export * from '@/service/query/locations';
export * from '@/service/query/menus';
export * from '@/service/query/nameBoards';
export * from '@/service/query/parties';
export * from '@/service/query/screens';
export * from '@/service/query/trucks';
export * from '@/service/query/units';
