-- One-time upgrade when app_entity_field still has data_type and screen tables use format_hint.
-- Prefer: dotnet ef database update (migration AddAppFieldDataTypeAndComponentColumns).
-- Use this script only when applying DDL manually via psql.

CREATE TABLE IF NOT EXISTS app_field_data_type (
    field_data_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code character varying(32) NOT NULL,
    display_name character varying(128) NOT NULL,
    description text,
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_app_field_data_type_type_code
    ON app_field_data_type (type_code);

\ir ../app_field_data_type/insert.sql

ALTER TABLE app_entity_field
    ADD COLUMN IF NOT EXISTS field_data_type_id integer;

UPDATE app_entity_field f
SET field_data_type_id = t.field_data_type_id
FROM app_field_data_type t
WHERE f.field_data_type_id IS NULL
  AND t.type_code = f.data_type;

ALTER TABLE app_entity_field
    ALTER COLUMN field_data_type_id SET NOT NULL;

ALTER TABLE app_entity_field
    DROP COLUMN IF EXISTS data_type;

ALTER TABLE app_entity_field
    DROP CONSTRAINT IF EXISTS fk_app_entity_field_app_field_data_type_field_data_type_id;

ALTER TABLE app_entity_field
    ADD CONSTRAINT fk_app_entity_field_app_field_data_type_field_data_type_id
    FOREIGN KEY (field_data_type_id)
    REFERENCES app_field_data_type (field_data_type_id)
    ON DELETE RESTRICT;

ALTER TABLE app_entity_screen_column
    RENAME COLUMN format_hint TO column_component;

ALTER TABLE app_entity_screen_field
    RENAME COLUMN format_hint TO field_component;
